/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.device;

import gui.Home;
import hot.domain.entities.device.Device;
import hot.domain.entities.device.commands.DeviceOffCommand;
import hot.domain.entities.device.commands.DeviceOnCommand;
import hot.domain.entities.device.commands.ICommand;
import hot.domain.entities.device.extensions.IActuator;
import hot.domain.entities.house.adapters.SwingHouseAdapter;

/**
 *
 * @author Me
 */
public class DeviceDetailsDialog extends javax.swing.JDialog {

    private final SwingHouseAdapter swingHouseAdapter;

    private final Device device;

    private final boolean firstInit;

    /**
     * Creates new form DeviceDetailsDialog
     *
     * @param parent
     * @param modal
     * @param device
     */
    public DeviceDetailsDialog(Home parent, boolean modal, Device device) {

        super(parent, modal);

        swingHouseAdapter = parent.getSwingHouseAdapter();

        initComponents();

        this.device = device;

        deviceNameTextField.setText((String) parent.getAvailableDevicesComboBox().getSelectedItem());

        if (device instanceof IActuator) {
                
            if (((IActuator) device).isOn()) {
                turnOnDeviceToggleButton.doClick();
            }
        } else {
            deviceNameTextField.setVisible(false);
            turnOnDeviceToggleButton.setVisible(false);
        }

        firstInit = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deviceNameTextField = new javax.swing.JTextField();
        turnOnDeviceToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Device Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Device Details"));

        jLabel1.setText("Name:");

        deviceNameTextField.setEnabled(false);

        turnOnDeviceToggleButton.setText("Turn On");
        turnOnDeviceToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOnDeviceToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deviceNameTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(turnOnDeviceToggleButton))
                        .addGap(0, 262, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deviceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turnOnDeviceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void turnOnDeviceToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOnDeviceToggleButtonActionPerformed
        if (turnOnDeviceToggleButton.getText().equals("Turn On")) {
            if (firstInit) {
                ICommand command = new DeviceOnCommand(
                        ((IActuator) device)
                );
                command.execute();
            }
            turnOnDeviceToggleButton.setText("Turn Off");
        } else {
            if (firstInit) {
                ICommand command = new DeviceOffCommand(
                        ((IActuator) device)
                );
                command.execute();
            }
            turnOnDeviceToggleButton.setText("Turn On");
        }
    }//GEN-LAST:event_turnOnDeviceToggleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deviceNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton turnOnDeviceToggleButton;
    // End of variables declaration//GEN-END:variables
}
